### PR TITLE
feat(climate): create climate card

### PR DESCRIPTION
**Pull request by piitaya**
## Description
- [x] display hvac mode
- [x] display hvac action
- [x] display current temperature
- [x] temperature control
- [x] temperature range control
- [x] mode control

## Types of changes

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 🌎 Translation (addition or update a translation)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have tested the change locally.

### CODE REVIEW

**Comment by mattkerrison** [comment]
What else is needed for this? it looks like the mode & basic temp control have now been added?

**Comment by piitaya** [comment]
There are documentation and some manual tests missing. But I will be unavailable in the next few days so I couldn't finish it now 😅

**Comment by DenyThis** [comment]
Hey Paul! Gave the climate card a shot on my local setup and definitely love it. Great job!! 

One small issue I did find with it was that it doesn't seem to play super well with the temperature control for the heat_cool mode when I'm using the horizontal layout. I've attached a screenshot for reference. 



Also, selecting more than 4 modes to chose from seem to have a similar (albeit not so bad) effect, as the buttons get significantly compressed. This one I think we could live with, but I'm also adding it just in case it's not the behavior you're looking for.

**Comment by piitaya** [comment]
Thanks 😊
Yep, I think you should use the default layout or horizontal layout when there are lot of HVAC modes or dual temperature control.

The vertical layout works well with single temperature control 😅

[Screenshot_20220716-222558.jpg](https://user-images.githubusercontent.com/5878303/179370954-48550bd1-7c11-490e-aadb-445ecc3c91a3.jpg)

I didn't tested the fahrenheit unit but I'm happy to see that it work well on your screenshots.

There is just some documentation missing to merge the PR. I will do it as soon as find time for this !
It's just a first draft, there is some missing point like preset modes to add in the future.

**Comment by DenyThis** [comment]
Awesome!! Thanks for the tips, I'll def give em a shot, although I really like the horizontal layout 😁 Looking forward for the release!

**Comment by DenyThis** [comment]
Oh! Here's some screenshots for horizontal mode. I think it really is the best one for the climate card 😍

**Comment by ulic75** [comment]
What do you think about adding color to the temperature unit numbers, climate blue for cool and climate orange for heat?  Without the color it still logically it make since since one is higher than the other, but I think the color would just add some clarity and make the card a bit more beautiful looking.

**Comment by piitaya** [comment]
@ulic75 I merged to PR to provide a first version of the card. Sure we can improve the look and feel 🙂. I'm not sure about the color of the input color but it might be worth doing some testing.

**Comment by thewolf-oz** [comment]
This is looking good! Would it be possible to have the option to collapse the card when turned off like lighting controls?

**Comment by piitaya** [comment]
Yep that can be a improvement 🙂

**Comment by piitaya** [comment]
@thewolf-oz https://github.com/piitaya/lovelace-mushroom/pull/620 👀

**Pull request merged**
