### PR TITLE
Feat: Badge to template card

### PR DESCRIPTION
**Pull request by Gnol86**
## Description
Add badge to template card
Documentation update
Localisation EN and FR update

image

image

## Related Issue
/

## Motivation and Context
I need this feat

## How Has This Been Tested

Tested locally and it's run !

## Types of changes

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [X] 🚀 New feature (non-breaking change which adds functionality)
- [X] 🌎 Translation (addition or update a translation)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have tested the change locally.

### CODE REVIEW

**Review by piitaya — APPROVED** [review]
Seems good to me 🙂

**Comment by Gnol86** [comment]
When do you think the production version will be released?

**Comment by piitaya** [comment]
I planned to do a new version when https://github.com/piitaya/lovelace-mushroom/pull/528 is completed but I can release on today for your addition 🙂

**Comment by piitaya** [comment]
I released the [1.10.0 version](https://github.com/piitaya/lovelace-mushroom/releases/tag/v1.10.0) 🚀

**Comment by Gnol86** [comment]
Thanks !

**Comment by piitaya** [comment]
Should be a cache issue. Try install reinstall mushroom or delete manually the mushroom folder/files in community folder.

**Comment by bafplus** [comment]
This is great! Thanks! Can this also be added to ,say, light card? AT the moment it only works in template card so if you want to use it you also need to build said light card from scratch...

**Comment by piitaya** [comment]
Why do you want badge for light card ? 🤔

**Comment by bafplus** [comment]
Say i have a toilet with motion sensor, so i have a light-card for it, i would love to display the icon when motion is triggered.

**Comment by piitaya** [comment]
To keep mushroom simple, domain oriented cards (light, alarm, etc...) are linked to only one entity. It's to complicated to handle all users use cases. That's why template card was created.

**Comment by neilimixamo** [comment]
Amazing feature. Thank you so much ! 👏

**Pull request merged**
