### PR TITLE
feat(chips): add alignment

### LINKED ISSUE #111: [Chips] Select chips horizontal alignment
**Is your feature request related to a problem? Please describe.**
User should be able to select the horizontal alignment of the chips.

**Describe the solution you'd like**
Default would be as it is, `line start`, but user could select `line end`, `center` or `justify`

**Additional context**
The issue: https://github.com/piitaya/lovelace-mushroom-themes/issues/2

### PR DESCRIPTION
**Pull request by bemble**
Allow user to set alignment of chips.

closes #111

### CODE REVIEW

**Review by piitaya — APPROVED** [review]
Nice !
What about left, right instead of line-end line-start? 
We can create a alignment picker like the color picker too but it can be future refactoring 😁

**Comment by pierrecle** [comment]
> Nice ! What about left, right instead of line-end line-start? We can create a alignment picker like the color picker too but it can be future refactoring 😁

Because `line-start` and `line-end` let us free about LTR and RTL stuff.
For the alignment picker, I thought about it and my conclusion is "if it's applicable for another component, sure we'll create an alignment picker".

**Comment by piitaya** [comment]
Or just start and end like flex stuff ?

**Comment by pierrecle** [comment]
> Or just start and end like flex stuff ? Or row instead of line ? I think "ligne" translation is "row" in this case.

`justify-content` uses `line-start` and `line-end`, that's why I used it :)

**Comment by piitaya** [comment]
> > Or just start and end like flex stuff ? Or row instead of line ? I think "ligne" translation is "row" in this case.
> 
> `justify-content` uses `line-start` and `line-end`, that's why I used it :)

It's flex-start and flex-end 😅

**Comment by pierrecle** [comment]
> > > Or just start and end like flex stuff ? Or row instead of line ? I think "ligne" translation is "row" in this case.
> > 
> > 
> > `justify-content` uses `line-start` and `line-end`, that's why I used it :)
> 
> It's flex-start and flex-end 😅

Hahaha, indeed, too tired :)
I change the translation and property values.

**Review by piitaya — APPROVED** [review]

**Pull request merged**
