### PR TITLE
fix: updated Russian translation for alignment

### LINKED ISSUE #1084: [Bug]: Russian translation for alignment incorrect
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

- "Align to start" == "Align to left edge" == "По __левому__ краю"
- "Align to end" == "Align to right edge" == "По __правому__ краю"

### Expected Behavior

- "Align to start" == "Align to left edge" == "По __правому__ краю"
- "Align to end" == "Align to right edge" == "По __левому__ краю"

### Steps To Reproduce

1. Change language to Russian
2. Edit biscuits (?) card (pill nav)
3. Select alignment drop-down
4. Select "По левому краю" (Align to left edge)
5. Stuff aligns to right side

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by alryaz**
## Description

Updated Russian translation to reflect actual alignment.
Translations are, in my opinion, swapped.

_Align to start_ (left edge) is translated as "right edge", whereas _align to end_ (right edge) is translated as "left edge".

## Related Issue

This PR fixes or closes issue: fixes #1084 

## Motivation and Context

Confusing behavior when setting up cards.

## How Has This Been Tested

Renamed these in my own local copy.

## Types of changes

-   [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [ ] 🚀 New feature (non-breaking change which adds functionality)
-   [x] 🌎 Translation (addition or update a translation)
-   [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] I have tested the change locally.
-   [ ] I followed [the steps](https://github.com/piitaya/lovelace-mushroom#maintainer-steps-to-add-a-new-language) if I add a new language .

### CODE REVIEW

**Review by piitaya — CHANGES_REQUESTED** [review]
The translations is "right" or "left". Mushroom is using start and end because it depends of the RTL language support. Can you update it with start and end ?

**Review by piitaya — APPROVED** [review]

**Comment by alryaz** [comment]
Updated my branch accordingly.

I didn't, however, find the most appropriate way to express alignment to "start"/"end" because I couldn't find the most appropriate noun to express what's getting aligned (as opposed to what the thing is getting aligned to.

**Comment by piitaya** [comment]
Here's the css documentation for alignment : https://developer.mozilla.org/ru/docs/Web/CSS/justify-content#%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81

Unfortunately I don't speak Russian but may be this can help you for the right translation 🙂

**Comment by alryaz** [comment]
I did use this as a reference, however the use of a genitive form of "container" noun __("контейнера")__ helps comprehension, whereas I'm not sure what to insert here as a substitute (the necessity of a noun is also questionable).

Anyway, the translation is more or less correct, and the presence of a noun is a creature comfort at best.

I also did remove some extra hyphenation which is invalid for word combination "by default" __("по умолчанию")__.

**Pull request merged**
