### PR TITLE
add portuguese brazilian language support

### PR DESCRIPTION
**Pull request by hudsonbrendon**

### CODE REVIEW

**Comment by piitaya** [comment]
Hello 🙂
Thank's for your contribution. Don't forget to include your file in the [localize file](https://github.com/piitaya/lovelace-mushroom/blob/main/src/localize.ts). 🙂

**Comment by hudsonbrendon** [comment]
> Hello 🙂 Thank's for your contribution. Don't forget to include your file in the [localize file](https://github.com/piitaya/lovelace-mushroom/blob/main/src/localize.ts). 🙂

Done, I thank you.

**Comment by bemble** [comment]
@hudsonbrendon Thanks for your contribution. @piitaya is finishing his PR #132 , after that, is it possible for you to add the fields we add in #131 and #132? To add an updated translation.

**Comment by hudsonbrendon** [comment]
> @hudsonbrendon Thanks for your contribution. @piitaya is finishing his PR #132 , after that, is it possible for you to add the fields we add in #131 and #132? To add an updated translation.

Hi, yes I can, as soon as possible I will update, thank you.

**Comment by hudsonbrendon** [comment]
@bemble PR fixed, I added the new fields

**Pull request merged**
