### PR TITLE
feat(template): add support line break for template

### PR DESCRIPTION
**Pull request by piitaya**
Add line break support for template secondary info and for title card

### CODE REVIEW

**Comment by pullaf** [comment]
Is this live?
I'm running 1.3.2 but the `.secondary` CSS still has `white-space: nowrap;`
If I change it through Chrome's Dev tool to match your commit it works as intended, but not out of the box.. how can I fix this?

**Comment by Beylie** [comment]
Is it possible to add a line break to the primary as well in template cards? I was using chip cards but switched over to template cards and I now have this. Top line are chips, bottom templates:

image

**Comment by NicoLeOca** [comment]
Bonjour @piitaya
Is there any chance this could be added to template chips too, please?

**Comment by xbmcnut** [comment]
Is it at all possible to set the position for the line break?
```
  - type: custom:mushroom-template-card
    primary: Version Information
    secondary: >-
      Installed v{{ state_attr('update.ds_dsm_update', 'installed_version')}}
      Latest v{{ state_attr('update.ds_dsm_update', 'latest_version')}}
    icon: mdi:package-variant-closed
```

image

**Pull request merged**
