### PR TITLE
Feature/scenes card

### PR DESCRIPTION
**Pull request by acesyde**
Draft Scenes card

- Support scene
- Support script

image
image

### CODE REVIEW

**Comment by piitaya** [comment]
I don't known if the box shadow inside the card is needed.
I'm very busy for now, I don't have time to review all the great job you are doing. May be we can sync each other in discord or something about the futur roadmap? 🙂 There is a lot of issues but sorting is required 😅

**Comment by piitaya** [comment]
May be the outside border is not needed 🙂

**Comment by greghesp** [comment]
I think the container should go. The card itself should simply just be the oval and nothing else?

Does the width auto adjust too? What if the scene name is longer than 5 char? Some of my name's are quite long

**Comment by piitaya** [comment]
You can have the same with mushroom card inside vertical stack in card.

**Comment by acesyde** [comment]
You can use stack in card or vertical stack in card (if you want to remove all borders) or maybe just the official card stack for that

**Comment by hudsonbrendon** [comment]
> Você pode usar pilha em cartão ou pilha vertical no cartão (se você quiser remover todas as bordas) ou talvez apenas a pilha oficial de cartões para isso
> 
> 

Hi, could you share the code for this card?

**Comment by hudsonbrendon** [comment]
> You can use stack in card or vertical stack in card (if you want to remove all borders) or maybe just the official card stack for that
> 
> 

Hi, could you share the code for this card?

**Comment by mersocarlin** [comment]
@acesyde 
do you have a sample of how to build "You can use stack in card or vertical stack in card"?

**Pull request closed without merging**
