### PR TITLE
Create nb

### PR DESCRIPTION
**Pull request by hwikene**
Norwegian translation

### CODE REVIEW

**Comment by piitaya** [comment]
Hi 🙂 I think the import in the localize.ts file is missing.

**Comment by hwikene** [comment]
Hi! You are correct. Sorry my bad 🙂

**Comment by hwikene** [comment]
Hi! Do you change the name? Can find how to change it :)

**Comment by piitaya** [comment]
You can look at other translation PR to find how to add a new translation : https://github.com/piitaya/lovelace-mushroom/pull/224/files 🙂

**Comment by piitaya** [comment]
I added [some instructions](https://github.com/piitaya/lovelace-mushroom#maintainer-steps-to-add-a-new-language) for adding a new language. Can you make a pull request with the two changes (file + localize file)? Don't forget to add the `json` extension to your file.

**Pull request closed without merging**
