### PR TITLE
Light Card - Add Support for RGBW and RGBWW white control

### PR DESCRIPTION
**Pull request by PaoloTK**
## Description

Add slider control on the light card for the white component(s) of RGBW and RGBWW lights. 
This is a follow-up to PR #809.

## Related Issue

https://github.com/piitaya/lovelace-mushroom/issues/747

This PR fixes or closes issue: fixes 747

## Motivation and Context

At the moment the light card can fully control white lights, CCT lights, RGB lights and RGB+CCT lights, but not RGBW or RGBWW lights. I have a lot of those kinds of lights at home and needed a way to control them with Mushroom.

## How Has This Been Tested

Demo instance and my own instance.

## Types of changes

-   [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [x] 🚀 New feature (non-breaking change which adds functionality)
-   [ ] 🌎 Translation (addition or update a translation)
-   [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x] My code follows the code style of this project.
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
-   [x] I have tested the change locally.
-   [ ] I followed [the steps](https://github.com/piitaya/lovelace-mushroom#maintainer-steps-to-add-a-new-language) if I add a new language .

### CODE REVIEW

**Comment by timo-sztyler** [comment]
Thank you very much! I was looking for this -I pulled your fork and build the js file. The parameter "show_white_control" is recognized but for some reason the slider is not visible. I deleted the cache. Do you know by any chance the reason? Thank you!

**Comment by PaoloTK** [comment]
> Thank you very much! I was looking for this -I pulled your fork and build the js file. The parameter "show_white_control" is recognized but for some reason the slider is not visible. I deleted the cache. Do you know by any chance the reason? Thank you!
> 
> Edit: Found the local issue -it works! :)

Good stuff, let me know if you encounter any bug or would like to see any changes.

**Comment by timo-sztyler** [comment]
I am not sure if this is directly related: With this modifcation, I can control the white led (RGBW) but I don't see an option to disable RGB. For example, when i make the strip glow red (with the standard features of the mushroom card), and then use your slider for controlling the White channel (the fourth one) then it stays red(-ish). Maybe I miss something, but I would like to disable RGB sometimes and only use the (warm) white channel. I am happy about any feedback or thoughts. Thank you!

**Comment by PaoloTK** [comment]
> I am not sure if this is directly related: With this modifcation, I can control the white led (RGBW) but I don't see an option to disable RGB. For example, when i make the strip glow red (with the standard features of the mushroom card), and then use your slider for controlling the White channel (the fourth one) then it stays red(-ish). Maybe I miss something, but I would like to disable RGB sometimes and only use the (warm) white channel. I am happy about any feedback or thoughts. Thank you!

Yes, that's a fair point and something I've thought about and was actually looking into yesterday. Mushroom was designed with RGB+CCT strips in mind, and for those when you switch between the 2 modes the other is automatically disabled, so it's a non issue. This is not the case for RGBW or RGVWW lights.

My idea was to implement "hold button to toggle" on the buttons (RGB, W, CW, WW). What do you think?

**Comment by timo-sztyler** [comment]
I think that might work -should be fine from a usability point of view. Please let me know in case I can help somehow.

**Comment by PaoloTK** [comment]
> I think that might work -should be fine from a usability point of view. Please let me know in case I can help somehow.

Another option would be to implement a color brightness slider? But that means adding way too many buttons in my opinion. The toggle idea works if one wants to fully disable the RGB, but offers no way to control the brightness of the RGB.

**Comment by piitaya** [comment]
That's one of the reason I didn't implement RGBW and RGBWW in Mushroom. Too much control for a small card 😕

**Comment by PaoloTK** [comment]
> That's one of the reason I didn't implement RGBW and RGBWW in Mushroom. Too much control for a small card 😕

Holding buttons to toggle is a good middle ground IMHO. Although I think having an additional button is not the end of the world. No one is forcing the user to enable every button for a single slider. One could have multiple sliders controlling the same light and then use stack-in-card or similar to combine them.

**Comment by nkou123** [comment]
I am have only RGBWW controllers in my house. With the present Light Card, I still cannot use the functionalities of my RGBWW controller and is not working correctly when I change the brightness. I need two brightness controls, one for the RGB and one for the White channel and on some I have also and RGB W & WW so imagine how difficult is to control it. The default light popup card of HA controls everything correctly although but your card no.

How can I install the changes you did here? I am not sure how and what to download.
Will they survive an update through HACS?

**Comment by PaoloTK** [comment]
> I am have only RGBWW controllers in my house. With the present Light Card, I still cannot use the functionalities of my RGBWW controller and is not working correctly when I change the brightness. I need two brightness controls, one for the RGB and one for the White channel and on some I have also and RGB W & WW so imagine how difficult is to control it. The default light popup card of HA controls everything correctly although but your card no.
> 
> How can I install the changes you did here? I am not sure how and what to download. Will they survive an update through HACS?

Sorry, I haven't spent any more time developing this feature since it's unlikely to be merged. You'd need to compile it yourself.

**Pull request closed without merging**
