### PR TITLE
feat(chip): improve stack in card support

### PR DESCRIPTION
**Pull request by piitaya**
## Description
Convert chip to standard ha-card. This improve support for card like `vertical-stack-in-card`.
Also, if chips-card are inside ha-card, border are removed to avoid card_mod usage.

## Example : 
image

```yaml
type: custom:vertical-stack-in-card
cards:
  - type: custom:mushroom-light-card
    entity: light.bed_light
  - type: custom:mushroom-chips-card
    alignment: justify
    chips:
      - type: entity
        entity: sensor.outside_temperature
        icon_color: red
      - type: entity
        entity: sensor.iphone_de_paul_battery_level
        icon_color: grey
```

## Types of changes

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 🌎 Translation (addition or update a translation)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have tested the change locally.

### CODE REVIEW

**Comment by Jmjm80** [comment]
Im havent an issue with a custom theme:

Chips background still shows: (by the way, i really all the great work you're doing)
SCR-20220519-10a

**Comment by piitaya** [comment]
Have you added this options to vertical stack in card?
```yaml
styles:
  '--chip-box-shadow': none
  '--chip-background': none
  '--chip-spacing': 0
```

**Comment by Jmjm80** [comment]
> 

Yes, I did.

FE7F3D41-EBDF-4C52-86D6-0CDFB4B3CAEE

**Comment by piitaya** [comment]
And what is your Mushroom version?

**Comment by Jmjm80** [comment]
V1.8.7

**Comment by Idan37S** [comment]
> > 
> 
> Yes, I did.
> 
> FE7F3D41-EBDF-4C52-86D6-0CDFB4B3CAEE

You are using stack-in-card,
Try using vertical-using-in-stack and it will probably work

**Comment by GitHubGoody** [comment]
Same issue here in the top-left corner (and many other cards)...
image

I'm on v1.8.7 and was previously able to use...

```
style: |
  ha-card {box-shadow: 0px 0px;}
```
...to remove the border shadow on Mushroom Chips in stack-in-cards (not vertical-stack-in-cards as I see in the previous post).

Considering stack-in-cards are meant to work in vertical or horizontal mode since they were meant to replace vertical-stack-in-cards...

image

...I'd still like to figure out the proper syntax and/or request a change in Mushroom Chip Cards to make them compatible again. I think it'll be great to not have to remove the border for each chip card once I can get it working. ;-)

Here's the syntax I'm trying (I've also tried putting '0px 0px' in place of 'none' for the box-shadow property...didn't work):

```
- type: custom:stack-in-card
  mode: vertical
  styles:
    '--chip-box-shadow': none
    '--chip-background': none
    '--chip-spacing': 0
  cards:
      # Status Chips
    - type: custom:mushroom-chips-card
      chips:
        - type: template
          entity: binary_sensor.study_occupancy
          icon: >-
            {{ iif(is_state('binary_sensor.study_occupancy','on'),
            'mdi:account-check', 'mdi:account-cancel-outline') }}
          icon_color: '{{ iif(is_state(''binary_sensor.study_occupancy'',''on''), ''green'', ''grey'') }}'
          tap_action:
            action: more-info
```

I appreciate any help.

**Comment by piitaya** [comment]
One example with stack-in-card. We need to use `card_mod` :
```yaml
type: custom:stack-in-card
cards:
  - type: custom:mushroom-chips-card
    card_mod: 
      style: |
        ha-card {
          --chip-box-shadow: none;
          --chip-background: none;
          --chip-spacing: 0;
        }
    chips:
      - type: entity
        entity: sensor.outside_temperature
        icon_color: red
      - type: light
        entity: light.bed_light

```

**Comment by smiller171** [comment]
card_mod still isn't doing it for me. Drop shadow won't go away

**Comment by smiller171** [comment]
Ok, I didn't initially realize that `card-mod` was something I needed to install. After getting it set up it still didn't work as @piitaya described. This is what I finally got to work:

```yaml
type: custom:stack-in-card
mode: vertical
card_mod:
  style:
    "hui-vertical-stack-card$ mushroom-chips-card":
      "$ *":
        "$ mushroom-chip$": |
          ha-card {
            --ha-card-box-shadow: none;
          }
cards:
  - type: custom:mushroom-title-card
    title: Front Door
    alignment: center
    subtitle: ''
  - type: custom:mushroom-chips-card
    chips:
      - type: entity
        entity: lock.front_door_lock
      - type: entity
        entity: sensor.doorbell_last_motion
        icon: mdi:motion-sensor
      - type: entity
        entity: sensor.doorbell_last_ding
        icon: mdi:bell-ring-outline
      - type: alarm-control-panel
        entity: alarm_control_panel.home_alarm
    alignment: center
```

image

**Comment by smiller171** [comment]
Here you go, default theme with mushroom `1.8.8`
```yaml
type: custom:stack-in-card
mode: vertical
cards:
  - type: custom:mushroom-title-card
    title: Front Door
    alignment: center
    subtitle: ''
  - type: custom:mushroom-chips-card
    card_mod:
      style: |
        ha-card {
          --chip-box-shadow: none;
          --chip-background: none;
          --chip-spacing: 0;
        }
    chips:
      - type: entity
        entity: sensor.doorbell_last_motion
        icon: mdi:motion-sensor
      - type: entity
        entity: sensor.doorbell_last_ding
        icon: mdi:bell-ring-outline
    alignment: center
  - type: custom:mushroom-chips-card
    card_mod:
      style: |
        ha-card {
          --chip-box-shadow: none;
          --chip-background: none;
          --chip-spacing: 0;
        }
    chips:
      - type: entity
        entity: lock.front_door_lock
      - type: alarm-control-panel
        entity: alarm_control_panel.home_alarm
    alignment: center
```

image

**Comment by smiller171** [comment]
Using Chrome on MacOS with HASS running on RasPi. I wonder if there's CSS added by another extension breaking it for me?

**Comment by piitaya** [comment]
Maybe. I only have `card_mod` and `stack-in-card` installed on my test env.

**Comment by smiller171** [comment]
This seems to actually work now. Not sure what changed

**Pull request merged**
