### PR TITLE
Fixed broken emojis

### PR DESCRIPTION
**Pull request by StanlyLife**
Added 2 new emojis for:
entity- & cover card

### CODE REVIEW

**Comment by bdr99** [comment]
What was wrong with the emojis before? They looked fine to me.

**Comment by StanlyLife** [comment]
image
Chrome version 100 - windows

**Comment by bdr99** [comment]
Maybe your version of Windows 10 is too old. Which specific version of Windows 10 are you using?

**Comment by StanlyLife** [comment]
image

**Comment by bdr99** [comment]
20H2 is a pretty old build of Windows 10. If you upgrade to the newest version, I think you will be able to see those emoji.

**Comment by StanlyLife** [comment]
Great! closed

**Pull request closed without merging**
