### PR TITLE
feat(humidifier): add humidifier support

### LINKED ISSUE #379: [Feat]: Add humidifier card
**Is your feature request related to a problem? Please describe.**
Provide a humidifier card

**Describe the solution you'd like**
Provide a humidifier card

**Describe alternatives you've considered**
Use the current official humidifier card

### PR DESCRIPTION
**Pull request by acesyde**
## Description
Add humidifier / dehumidifier card support

humidifier-dark
humidifier-light

## Related Issue

Fixes #379 

## Motivation and Context
Provide a mushroom card for humidifier / dehumidifier

## How Has This Been Tested
With hassio in local

## Types of changes

- [ ] 🐛Bug fix (non-breaking change which fixes an issue)
- [x] 🚀New feature (non-breaking change which adds functionality)
- [x] 🌎 Translation (addition or update a translation)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have tested the change locally.

### CODE REVIEW

**Comment by acesyde** [comment]
@piitaya ready to review

**Comment by NimlothPL** [comment]
You may want to change title: Lock ;)

**Comment by acesyde** [comment]
@piitaya based on MushroomBaseElement R2R :)

**Comment by anhnvme** [comment]
@piitaya please accept this pull. I'm waitting this card for long time. Thank you !

**Review by piitaya — COMMENTED** [review]
Nice 🙂
Is it possible to remove the button control? Fan and light doesn't have `on/off` buttons because it's possible to toggle it using `tap_action`.

@anhnvme I do this on my free time so I can't be always reactive 😅

**Comment by anhnvme** [comment]
> 

Yes i know that. I see pull commit and wait for long time before I mention you. :D thank for reply

**Comment by acesyde** [comment]
@piitaya  . @anhnvme  done ;)

**Review by piitaya — APPROVED** [review]

**Pull request merged**
