### PR TITLE
Add template badge

### PR DESCRIPTION
**Pull request by piitaya**
## Description

👀

## Related Issue

This PR fixes or closes issue: fixes #

## Types of changes

-   [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [x] 🚀 New feature (non-breaking change which adds functionality)
-   [ ] 🌎 Translation (addition or update a translation)
-   [ ] ⚙️ Tech (code style improvement, performance improvement or dependencies bump)
-   [ ] 📚 Documentation (fix or addition in the documentation)
-   [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have tested the change locally.
-   [ ] I followed [the steps](https://github.com/piitaya/lovelace-mushroom#maintainer-steps-to-add-a-new-language) if I add a new language .

### CODE REVIEW

**Comment by bkbilly** [comment]
Is it possible to change the background color of the card?
When using mushroom-chips-card, I use card_mod to set the background color like this:
```yaml
    card_mod:
      style: |
        ha-card {
          --chip-background: rgba(255,0,0,0.25);
        }
```

**Comment by piitaya** [comment]
As badges are not cards, I don't think it's possible to apply style using card mod.

**Comment by bkbilly** [comment]
Oh, that's a same.
Thank you for this budge, it is very nice!

**Comment by luixal** [comment]
That's the biggest thing I miss in this card set, being able to apply styles or at least, the color scheme to the background too :(

**Pull request merged**
