### PR TITLE
Add dropdown card

### PR DESCRIPTION
**Pull request by bryan-stewart**
## Description
I added a dropdown card
Entity light

## Related Issue
#704 

## Motivation and Context
Some people may like this card

## How Has This Been Tested
I have tested this card in Home Assistant

## Types of changes

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 🌎 Translation (addition or update a translation)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
-- I have only done translations for en and fr

## Checklist
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have tested the change locally.
-- I have no updated the main README but I have created its own docs with images

### CODE REVIEW

**Comment by PaoloTK** [comment]
Great card!

**Comment by synic2009** [comment]
Hi,
any news regarding this feature? It would be great to have this.

**Comment by bryan-stewart** [comment]
No news unfortunately.

**Comment by ankushg** [comment]
What a useful card! I specifically wanted to use it for the exact example you illustrated: leak sensors!

Any recommendation for how to use this card, even if it isn't merged into the official project?

**Comment by chris-wein** [comment]
Any news on this card? Would be really cool to have it!

**Comment by RickeyWard** [comment]
bump! this is a nice card! would love to see this get merged 👍

**Comment by skycryer** [comment]
Any news here, I need drop-downs and I do not want to use the input-boolean version with conditional component and spam my helper list. This one looks exactly like what I need.

**Pull request closed without merging**
