### PR TITLE
Alarm control panel code dialog

### LINKED ISSUE #787: [Feature]: show keypad only for disarming in alarm card
### Is your feature request related to a problem?

My alarm only requires the code for disarming.

### Describe the solution you'd like

Provide a configuration property to show the keypad in the alarm card only for disarming.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #1085: [Feature]: Only text input for alarm control panel card
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Right now, either you don't have a code for the Alarm Control Panel card, or you have a keypad and code. The keypad takes up a lot of space, plus looks bad in my theme.

### Describe the solution you'd like

An option to only show the code input box and not the keypad.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #1100: [Feature]: Alarm Panel
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Horizontal alarm card with only one button arm/disarm. Card option show keypad off.
When I press disarm I am getting error. Wrong Code.

### Describe the solution you'd like

Can we add default popup keypad when disarm button is pressed and code is required. New 2023.04 keypad looks good. Also can we update keypad look to newest version when card option show keypad is on.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #1290: [Feature]: Make Alarm Card display error message when entered code is invalid
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

If a user enters the incorrect alarm code, for example, when disarming the alarm, the code is simply cleared and no message to say the code was invalid is displayed.

### Describe the solution you'd like

I’d like to see the words “Invalid Code” or something similar displayed if an incorrect code is entered.

### Describe alternatives you've considered

The custom card from Alarmo has this feature, but I prefer the style of the mushroom cards, hence I’d prefer to use them.

### Additional context

_No response_

### LINKED ISSUE #1291: Alarm Card disarm button doesn't work if you have a code
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I have an Alarmo alarm set up with a mushroom alarm Card to control it. I can arm just fine with the mushroom card buttons as my alarm requires no code to arm, but if I then try to use the mushroom button to disarm, nothing happens. 

I understand you can make the card show a keypad when armed and this does work, but it completely ruins my layout as the card goes to 5x its size when armed

### Expected Behavior

If your alarm needs a code to disarm and you have the keypad hidden, pressing the disarm button should open a keypad in a popup so you can disarm

### Steps To Reproduce

1. Link an alarm to the mushroom alarm card that requires a pin to disarm
2. Disable alarm keypad on mushroom card so only the status and disarm button are shown when armed
3. Arm alarm
4. Press disarm button
Nothing happens

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Breaking changes

- Minimum HA version to use Mushroom is now `2024.3`
- `show_keypad` option is no longer available for alarm control panel card

## Description

Use dialog to ask code when arming and disarming. The code is only asked when needed.
Icons have been also updated to match the HA ones.

CleanShot 2024-05-30 at 12 46 22

## Related Issue

This PR fixes or closes issue: fixes #1291, fixes #1290, fixes #1100, fixes #1085, fixes #787

## Types of changes

-   [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [x] 🚀 New feature (non-breaking change which adds functionality)
-   [ ] 🌎 Translation (addition or update a translation)
-   [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have tested the change locally.
-   [ ] I followed [the steps](https://github.com/piitaya/lovelace-mushroom#maintainer-steps-to-add-a-new-language) if I add a new language .

### CODE REVIEW

**Comment by JDSymington** [comment]
"The code is only asked when needed."

Can you please explain what you mean with this statement? I used to be able to arm my alarm without entering a code. Now I have to enter the code and I don't see a way to disable this behaviour.

**Comment by piitaya** [comment]
@JDSymington Which integration are you using?

**Comment by JDSymington** [comment]
@piitaya I'm using ParadoxAlarmInterface (https://github.com/ParadoxAlarmInterface/pai)

**Comment by piitaya** [comment]
The default code behavior before was `no code required` but since `2024.6` it's `code required`. There is a dev blog article about it (https://developers.home-assistant.io/blog/2024/05/22/alarm_control_panel_validation). The custom integration needs to be updated by settings `code_arm_required` to `False` on the entity.

**Comment by JDSymington** [comment]
Thank you for pointing me in the right direction.

The solution was to enter a code in "Default code" field under HA alarm settings:
image

**Comment by piitaya** [comment]
Yes it's a workaround as the integration ask for code but doesn't verify it.

**Pull request merged**
