### PR TITLE
feat(lock): improve color rules for lock card

### PR DESCRIPTION
**Pull request by acesyde**
Feature : #351

- [x] Doc updated

### CODE REVIEW

**Comment by acesyde** [comment]
@piitaya ready to review

**Comment by piitaya** [comment]
Not sure we want to propose this. I think it's better to do this with a theme.

**Comment by acesyde** [comment]
hmmm I understand what you want to do ;)

**Comment by acesyde** [comment]
@piitaya like that ?

**Review by piitaya — APPROVED** [review]

**Pull request merged**
