### PR TITLE
feature: stack card

### PR DESCRIPTION
**Pull request by acesyde**
## Description
- Add maintained version of stack in card / vertical stack in card in Mushroom

## Related Issue
#505

## Motivation and Context
- Previous mentionned repositories are not maintained 

## How Has This Been Tested
 Locally

## Types of changes

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [x] 🌎 Translation (addition or update a translation)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have tested the change locally.

### CODE REVIEW

**Comment by piitaya** [comment]
If we import this feature in mushroom (I'm not sure about it). I don't think we must import code from others repositories. I think it's better to improve other repo.

**Comment by acesyde** [comment]
@piitaya for sure, but other repositories are not maintained :(

**Comment by piitaya** [comment]
Maybe we can create a new repository for that?

**Comment by piitaya** [comment]
I don't think I will have time to maintain this card so we will have the same issue as other repositories 🤣

**Comment by alessandroias** [comment]
I think this is a great idea: `stack-in-card` does not support a visual editor making the mushroom's efforts useless.
image
This card does not require much maintenance, but will allow, in the future, to build custom buttons (aesthetically similar to those of the `vacuum`,  `fan` or `media` card) that integrate with other cards and perform actions, for example you could attach buttons to a fan entity to set the various modes. I realize it's a rather advanced use, difficult to maintain and perhaps even rare, but it would solve many problems of the vacuum and fan cards.

**Comment by piitaya** [comment]
Vertical stack in card has a community. I prefer to help the developer to migrate to editor than copying his/her work.
Also I don't want users to install Mushroom only for the vertical stack in card included.

**Pull request closed without merging**
