### PR TITLE
Add white control for RGBW lights

### PR DESCRIPTION
**Pull request by PaoloTK**
## Description
This pull request adds a white brightness slider for RGBW lights. 

## Related Issue
https://github.com/piitaya/lovelace-mushroom/issues/747

## Motivation and Context
Right now the light card can control RGB and CCT lights, or RGB+CCT lights, but not the white channel(s) for RGBW or RGBWW lights. This pull request implements control for the white channel for RGBW lights. 

## How Has This Been Tested
Tested locally on demo HA instance.

## Types of changes

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 🌎 Translation (addition or update a translation)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have tested the change locally.

### CODE REVIEW

**Comment by PaoloTK** [comment]
I'm not sure what approach should be taken for RGB+W lights. There's no way to control the white value separately. I guess an option is to switch the light to white mode when you hit the button and then use the slider to control the light brightness value.

**Comment by PaoloTK** [comment]
@piitaya any feedback on this PR? I have RGBWW support ready to go as well but was waiting on feedback on this before submitting another PR.

**Comment by GHenry21** [comment]
Actually there is no way to have white at all, the closest thing you can have is full saturation cyan. 
No control on the saturation either, the color picked by the slider is at full sat. 
With esphome functionality `color interlock` :true you can force pure white (only dedicated w led lit) but it's shutted down as soon you pick a color from the slider

**Comment by PaoloTK** [comment]
> Actually there is no way to have white at all, the closest thing you can have is full saturation cyan. No control on the saturation either, the color picked by the slider is at full sat.

What do you mean by "there is no way to have white at all"? Are you talking about my PR? Because it works fine on my side. Please post more information about the light you're controlling so I can look into the problem.

> With esphome functionality `color interlock` :true you can force pure white (only dedicated w led lit) but it's shutted down as soon you pick a color from the slider

Color interlock turns the light into an RGB+W light, which my PR doesn't support at the moment.

**Comment by GHenry21** [comment]
Apologies for the late reply.
I have a RGBW strip controlled by Shelly RGBW2 with esphome.
What i mean with "there is no way to get the white color" is there is no white color on the color slider
immagine

The only way to get white is manually choosing it from ha color-wheel.

**Comment by PaoloTK** [comment]
> Apologies for the late reply. I have a RGBW strip controlled by Shelly RGBW2 with esphome. What i mean with "there is no way to get the white color" is there is no white color on the color slider immagine
> 
> The only way to get white is manually choosing it from ha color-wheel.

My testing has also been done on a Shelly RGBW2. Are you running my fork?

**Comment by GHenry21** [comment]
of course i'm running your fork otherwise i wouldn't comment here.

I also have another RGBW controller (thoose who came with tuya, center slider in the pic) flashed with esphome as you can see
they are all identical with no white...
immagine

Could esphome be the problem? (just thinking about that, since different device but same fw and same problem)

Can you plaese show me a slider with the white on it?

Esphome 2023.3.2
Home Assistant 2023.4.6

**Comment by timdonovanuk** [comment]
Still an bug - using an WLED led in HA with this card. No way to select white light! But two ways to select red lights 😕 

Whites could be at either end to be honest. 

image

**Pull request closed without merging**
