### PR TITLE
Allow customizing badge, button, shape, slider sizes

### PR DESCRIPTION
**Pull request by redphx**
## Description
Allows customizing icon sizes of badge, button, shape, slider by declaring these variables in theme YAML:  
- mush-badge-size
- mush-badge-icon-size
- mush-button-size
- mush-button-icon-size
- mush-shape-size
- mush-shape-avatar-size
- mush-shape-icon-size
- mush-slider-height

image
image
image

Should add these variables to theme's document after merging.

## Related Issue
Not entirely fix this issue (it applies to the entire theme, not just template card), but at least it lets users change icon sizes: https://github.com/piitaya/lovelace-mushroom-themes/issues/13

Also #385

## Types of changes

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 🌎 Translation (addition or update a translation)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have tested the change locally.

### CODE REVIEW

**Comment by redphx** [comment]
Is there any way to edit theme's YAML in dev environment?

**Review by piitaya — COMMENTED** [review]
Cool 👍 Thank you! 
I'm wondering if we must split the button and the slider height into 2 variables or not 😅

**Comment by piitaya** [comment]
> Is there any way to edit theme's YAML in dev environment?

I think you need to create a themes folder and put your theme yaml file in it.

**Comment by redphx** [comment]
> I'm wondering if we must split the button and the slider height into 2 variables or not 😅  
Those are two different cards so I think it's better to split them up?

**Comment by piitaya** [comment]
Button can be next to slider (fan card, light card). So I think it's better to have the same size for consistency. Maybe we can add a button ratio variable too if needed.

**Comment by redphx** [comment]
Feel free to update it!

**Comment by Jaguaza** [comment]
Sorry can someone explain me how to change the size of the icons. I still don't understand how to do it.

**Pull request merged**
