### PR TITLE
Enrich Weather chip

### LINKED ISSUE #1070: [Feature]: chip template weather image like in weather chip OR customize weather chip with templates
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I'd like to add some mor details to the weather chip, like humidity.

### Describe the solution you'd like

Possibility to customize the info of weather chip, like a template input field

### Describe alternatives you've considered

I tried a template chip, but I cannot access the weather svg icons from weather chip
image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by trizmark**
## Description

This PR enriches the Weather chip. It adds 2 new features:
- Ability to round the temperature. It uses less space and for some half a degree here or there makes no difference
- Ability to add additional information to the chip. The additional information can be templated, so one could add further information, like humidity or any sensor value.

## Related Issue

This PR fixes or closes issue: fixes #1070, but also adds extra functionality (temperature rounding)

## Motivation and Context

I love chips. I've got tons of them on my dashboard. In order to save some space I thought it would be a good idea to add  the possibility to round the temperature. 21.6C or 22C makes little difference, but it saves space.
I also wanted to add some additional information that are tied to the weather itself. Like compare the temperature forecast with the actual garden temperature. Or simply add the humidity value. Maybe the solar production forecast for today (once I've got my panels installed).

## How Has This Been Tested

Tested locally as described in the development server section of the readme.

## Types of changes

-   [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [x] 🚀 New feature (non-breaking change which adds functionality)
-   [ ] 🌎 Translation (addition or update a translation)
-   [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] I have tested the change locally.
-   [ ] I followed [the steps](https://github.com/piitaya/lovelace-mushroom#maintainer-steps-to-add-a-new-language) if I add a new language .

### CODE REVIEW

**Comment by piitaya** [comment]
Hello 👋
There is ton of issues of people that want template support for all others cards but it's a huge work... so I don't think this will happen anytime soon with the current architecture of Mushroom. Also, I don't want to add many options to cards to fix that issue because it will be confusing for most users to have ton of options.

**Comment by trizmark** [comment]
Would you be willing to accept the PR just for the 'round temperature' option or you think that's too much as well?

**Comment by piitaya** [comment]
IMO, the temperature precision should be set on the entity (like we have for sensors)
CleanShot 2023-06-16 at 13 45 02@2x

But I don't think it's possible for weather attributes... 😢

**Comment by trizmark** [comment]
Exactly! I tried to do this with the template chip, but that doesn't have access to the weather icons.
The only solution was to use two chips, one for the weather icon and one for the rounded temperature, but that's disjointed and uses more space that it should...

**Comment by piitaya** [comment]
What do you think about adding weather icon in template chip and card ?
https://github.com/piitaya/lovelace-mushroom/pull/1171

**Comment by trizmark** [comment]
I could have a go. I'll close this PR and open a new one once I manage to implement that.

**Comment by piitaya** [comment]
There already is a PR: https://github.com/piitaya/lovelace-mushroom/pull/1171

**Comment by trizmark** [comment]
I'm not very bright, am I... 🤦 
Great, looking forward to that feature in the next release!

**Pull request closed without merging**
