### PR TITLE
Entity picture option to chip entity card

### PR DESCRIPTION
**Pull request by skrynklarn**
Option to show the entity picture instead of icon in the chip entity card.

Increased image size to 24px instead of 1.5em that icons was. 1.5em image seemed to be very small.

Feel free to review and comment it.

### CODE REVIEW

**Comment by skrynklarn** [comment]
Loved this project and wanted to contribute. Don't want to be rude and understand people have other things to do. But 12 days now and no response from anyone. Lot of other PR that is later that have more activity. Seems that my help is not welcome or I'm doing something wrong? Have other PR with no response either.

**Comment by piitaya** [comment]
Sorry for the late reply. I think it's a good idea. Maybe we can use a size in `em` instead of `px` to support dynamic size when changing the chip size with theme ?

**Comment by chertvl** [comment]
this is what i was asking about.
thanks
https://github.com/piitaya/lovelace-mushroom/issues/146

**Comment by piitaya** [comment]
I merge the PR and will add entity_picture to entity card too.

**Pull request merged**
