### PR TITLE
fix(light): only show brightness controls if light support it

### LINKED ISSUE #136: Improve light card - Hide brightness slider when light is only On/Off
**Is your feature request related to a problem? Please describe.**
In the example bellow, all light cards will have slider for brightness event when the light is only able to On/Off.
In RGB lights this is already done, the control is only shown when light has RGB capability

**Describe the solution you'd like**
The card should discover light capabilities, and show controls accordingly. Currently is already done for RGB control.

**Describe alternatives you've considered**
n/a

**Additional context**
```
      - type: custom:auto-entities
        card:
          type: grid
          columns: 2
          square: false
        card_param: cards

        filter:
          include:
            - group: group.all_lights
              state: "on"
              options:
                type: custom:mushroom-light-card
                show_brightness_control: true
                use_light_color: true
                show_color_control: true
                hide_state: true
```
image

### PR DESCRIPTION
**Pull request by piitaya**
fix #136

### CODE REVIEW

**Comment by piitaya** [comment]
What's your entity attributes https://my.home-assistant.io/redirect/developer_states/ ?

**Comment by dirkpitt35** [comment]
Thanks for the reply. See below, do you need to see the individual entities within the group?

entity_id: light.led_kitchen_lantern, light.led_kitchen_kickboard
order: 6
friendly_name: Kitchen LED

**Comment by piitaya** [comment]
You only have theses attributes ?

I defined my light group like this :
```yaml
light:
  - platform: group
    name: Three Lights
    entities:
      - light.bed_light
      - light.ceiling_lights
      - light.christmas_tree_lights
```

The attributes :
```yaml
min_mireds: 153
max_mireds: 500
effect_list:
  - none
  - rainbow
supported_color_modes:
  - color_temp
  - hs
  - onoff
color_mode: color_temp
brightness: 180
color_temp: 380
hs_color:
  - 28.55
  - 67.974
rgb_color:
  - 255
  - 164
  - 81
xy_color:
  - 0.533
  - 0.389
entity_id:
  - light.bed_light
  - light.ceiling_lights
  - light.christmas_tree_lights
icon: mdi:lightbulb-group
friendly_name: Three Lights
supported_features: 4
```

And it works well 

image

**Comment by dirkpitt35** [comment]
Ah ok. I'm using the groups.yaml file to group them which I thought was the cleanest way.. very simple :)

kitchen_led:
    name: Kitchen LED
    entities:
        - light.led_kitchen_lantern
        - light.led_kitchen_kickboard

I'll try your approach later and see.

**Comment by piitaya** [comment]
> Ah ok. I'm using the groups.yaml file to group them which I thought was the cleanest way.. very simple :)
> 
> kitchen_led: name: Kitchen LED entities: - light.led_kitchen_lantern - light.led_kitchen_kickboard
> 
> I'll try your approach later and see.

It's better to use `platform group` instead of `group` because features with group are very limited.

**Comment by dirkpitt35** [comment]
I was just trying to keep my configuration.yaml as clean as possible but just did as you have suggested and it works great. Thanks for the pointer.

Matt

**Pull request merged**
