### PR TITLE
Add grid section support

### PR DESCRIPTION
**Pull request by piitaya**
## Description

Add support for the new grid section.

CleanShot 2024-03-05 at 17 20 37

## Types of changes

-   [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [x] 🚀 New feature (non-breaking change which adds functionality)
-   [ ] 🌎 Translation (addition or update a translation)
-   [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have tested the change locally.
-   [ ] I followed [the steps](https://github.com/piitaya/lovelace-mushroom#maintainer-steps-to-add-a-new-language) if I add a new language .

### CODE REVIEW

**Comment by ncodee** [comment]
Great work @piitaya! Could we also get grid support for the Title card?

Thanks

**Comment by piitaya** [comment]
It works, right? Do you have issue with the title card?

**Comment by ncodee** [comment]
> It works, right? Do you have issue with the title card?

Title card acts like a header and only works in 1x1 format. You can't put another card besides it with Sections unfortunately.

**Comment by piitaya** [comment]
It’s designed as a header. So it’s a limitation for now. Future releases of home assistant will provide a way to resize card.

**Pull request merged**
